### ISSUE TITLE
Pattern_Generator.py 실행 오류 문의 (불러온 mid에 가사 정보 없음)

### ISSUE THREAD

**Issue by MuHyeonSon** [CODEJIN/DiffSingerKR#2]
안녕하세요. 먼저 DiffSingerKR 프로젝트 공유에 대해 감사의 말씀을 드립니다.

해당 코드를 이용하면서 inference를 수행하기 위해 Pattern_Generator.py를 실행 중 line 231 에서 ```IndexError: list index out of range``` 오류가 발생하여 문의드리고 싶습니다.

오류 내용은 아래와 같습니다.

```
CSD_Fix:   0%|                                                                                                                      | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "Pattern_Generator.py", line 676, in <module>
    CSD_Fix(
  File "Pattern_Generator.py", line 269, in CSD_Fix
    if music[0][1] in [None, '', '<X>', 'J']:
IndexError: list index out of range
```

실행한 명령어는 ```python Pattern_Generator.py -hp Hyper_Parameters.yaml -csd D:/Datasets/rawdata_music/CSD``` 입니다.

README에 기재해 주신 CSD 링크에서 데이터셋을 다운로드 하였고, csd 내의 korean과 english 디렉토리 중 korean 내에 있는 csv, lyric, mid, txt, wav, metadata.json 을 DiffSingerKR/D:/Datasets/rawdata_music/CSD/ 경로에 넣어주었습니다.

Pattern_Generator 코드를 분석해보니, midi 파일 내의 가사 정보를 처리하도록 코드가 구현되어 있지만, 다운로드 받은 CSD파일의 mid파일들에는 가사정보를 찾을 수 없었습니다. 

혹시 mid 파일에 가사 정보를 넣어주는 처리를 따로 하는 것이 있는지, 아니면 제가 설정한 데이터 경로에 문제가 있었던 것인지 문의드리고 싶습니다.

감사합니다.

**Comment by CODEJIN** [comment]
안녕하세요.

코드의 CSD_Fix는 현재 내부적으로 수정한 데이터를 사용해서 오픈소스 데이터와 직접적으로 호환되지 않습니다.
금주 주말 중에 해결할 수 있도록 하겠습니다.

감사합니다.

**Comment by MuHyeonSon** [comment]
> 안녕하세요.
> 
> 코드의 CSD_Fix는 현재 내부적으로 수정한 데이터를 사용해서 오픈소스 데이터와 직접적으로 호환되지 않습니다. 금주 주말 중에 해결할 수 있도록 하겠습니다.
> 
> 감사합니다.

네. 답변 감사드립니다!

**Comment by CODEJIN** [comment]
CSD dataset이 fix되었습니다.
CSD/korean 을 경로로 지정하시면 됩니다.

**Comment by MuHyeonSon** [comment]
> CSD dataset이 fix되었습니다. CSD/korean 을 경로로 지정하시면 됩니다.

네 감사드립니다!! :)
